# Generated by Django 5.2.17 on 2026-09-17 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, help_text='ISO code, e.g. US / IN', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'employee info',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('TENURE', 'Tenure'), ('LEAVE', 'Leave'), ('LOCATION', 'Location'), ('COMPLIANCE', 'Compliance'), ('SHIFT', 'Shift'), ('BENEFIT', 'Benefit'), ('PAY_SCHEDULE', 'Pay schedule'), ('WORK_SCHEDULE', 'Work schedule')], max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'policy categories',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='PolicyOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='policies.policycategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('CONDITIONAL', 'Conditional')], default='CONDITIONAL', max_length=16)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, help_text='Null means currently active.', null=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='policies.policyoption')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_attribute', models.CharField(max_length=128)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not equals'), ('greater_than', 'Greater than'), ('less_than', 'Less than'), ('greater_than_or_equal', 'Greater than or equal'), ('less_than_or_equal', 'Less than or equal')], max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('combinator', models.CharField(choices=[('AND', 'And'), ('OR', 'Or')], default='AND', max_length=3)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='policies.rule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
