# Generated by Django 5.2.17 on 2026-09-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='policycategory',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['DEPARTMENT', 'TENURE', 'LEAVE', 'LOCATION', 'COMPLIANCE', 'SHIFT', 'BENEFIT', 'PAY_SCHEDULE', 'WORK_SCHEDULE'])), name='policycategory_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.CheckConstraint(condition=models.Q(('scope__in', ['GLOBAL', 'CONDITIONAL'])), name='rule_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='rule_valid_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='rulecondition',
            constraint=models.CheckConstraint(condition=models.Q(('operator__in', ['equals', 'not_equals', 'greater_than', 'less_than', 'greater_than_or_equal', 'less_than_or_equal'])), name='rulecondition_operator_valid'),
        ),
        migrations.AddConstraint(
            model_name='rulecondition',
            constraint=models.CheckConstraint(condition=models.Q(('combinator__in', ['AND', 'OR'])), name='rulecondition_combinator_valid'),
        ),
    ]
