# Generated by Django 5.2.17 on 2026-09-17 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policycategory_policycategory_type_valid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Display name for the UI.', max_length=255)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('bool', 'Bool')], max_length=16)),
                ('source', models.CharField(choices=[('attribute_table', 'Attribute table'), ('computed', 'Computed')], max_length=32)),
                ('enumerated', models.BooleanField(default=False, help_text='True when the UI should offer a fixed value list.')),
                ('compute_key', models.CharField(blank=True, help_text='Function name resolving the value when source=computed.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_type__in', ['text', 'number', 'date', 'bool'])), name='attribute_data_type_valid'), models.CheckConstraint(condition=models.Q(('source__in', ['attribute_table', 'computed'])), name='attribute_source_valid')],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='What the engine compares on.', max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(db_column='attribute_key', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='policies.attribute')),
            ],
            options={
                'ordering': ['attribute_id', 'sort_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('attribute', 'value'), name='attributevalue_unique_per_attribute')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(db_column='attribute_key', on_delete=django.db.models.deletion.PROTECT, related_name='employee_values', to='policies.attribute')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='policies.employeeinfo')),
            ],
            options={
                'ordering': ['employee_id', 'attribute_id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'attribute'), name='employeeattribute_unique_per_employee')],
            },
        ),
    ]
