# Generated by Django 5.2.17 on 2026-09-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_move_employee_columns_to_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='location',
        ),
    ]
